# Generated by Django 2.1.4 on 2019-11-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('zip_code', models.CharField(max_length=11)),
                ('default', models.BooleanField(choices=[(0, '非默认地址'), (1, '默认地址')], default=0)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('md5', models.CharField(max_length=192)),
            ],
            options={
                'verbose_name_plural': '图片',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('pid', models.IntegerField()),
                ('sname', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('citycode', models.CharField(blank=True, max_length=128, null=True)),
                ('yzcode', models.CharField(blank=True, max_length=128, null=True)),
                ('mername', models.CharField(max_length=128)),
                ('Lng', models.FloatField()),
                ('Lat', models.FloatField()),
                ('pinyin', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '城市表',
                'verbose_name_plural': '城市表',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
                ('grade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(1, '未注销'), (3, '已注销'), (2, '注销中')], default=1)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('gender', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('intro', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInformation',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=True, related_name='市外键', to='user.Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.ForeignKey(on_delete=True, related_name='县外键', to='user.Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=True, related_name='省外键', to='user.Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
